### PR TITLE
Add docs on not running on draft PRs

### PR DESCRIPTION
**Pull request by paddyroddy**
Unfortunately, I don't think we can do this in the action, but we can at least have it in the docs (and will adjust the templates)

### CODE REVIEW

**Comment by paddyroddy** [comment]
Forgot to add it to the workflows of _this_ repo. Will now mark as draft to test.

**Comment by paddyroddy** [comment]
And we're back

**Review by HChughtai — APPROVED** [review]
A shame that it can't be done at the action level, or at least defined centrally elsewhere.

**Comment by HChughtai** [comment]
Oh, it was in draft again - sorry!

**Comment by paddyroddy** [comment]
> A shame that it can't be done at the action level, or at least defined centrally elsewhere.

Yeah, I'm not sure if that is possible. Have fixed this now.

**Comment by paddyroddy** [comment]
I think I'm going to remove it from the README.md because it won't work without the special `types` thing we have here. But in the templates it'll have the full workflow.

**Review by HChughtai — APPROVED** [review]

**Pull request merged**
